version: "3"
services:
  proxy:
    image: nginx
    volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=rainier.com
    - NGINX_PORT=80
    - NGINX_ENTORYPOINT_QUIET_LOGS=1
  api:
    image: node
    volumes:
    - ./api:/usr/app
    - ./api/node_modules:/usr/app/node_modules
    ports:
    - "8080"
    command: "node /usr/app/index.js"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    volumes:
    - ./es/data:/usr/share/elasticsearch/data
    ports:
    - "9200"
    - "9300"
    environment:
    - discovery.type=single-node
  kb:
    image: docker.elastic.co/kibana/kibana:7.15.1
    ports:
    - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://es:9200"
      ELASTICSEARCH_HOSTS: '["http://es:9200"]'
    depends_on: 
    - "es"
